### PR TITLE
Updated core-lib + Implemented latest primitives

### PR DESCRIPTION
**Pull request by Hirevo**
This PR updates the core-lib submodule to the latest commit on its master branch.  
This PR also includes implementations for all of the latest primitives added since September 2020, for both interpreters.  

The implemented primitives are:

- `Integer>>#asDouble`
- `System>>#loadFile:`
- `System>>#hasGlobal:`
- `System>>#errorPrint:`
- `System>>#errorPrintln:`
- `System>>#printStackTrace`

**Depends on #22.**

### CODE REVIEW

**Comment by smarr** [comment]
There are also the basic interpreter tests, see for my earlier attempt: https://github.com/Hirevo/som-rs/compare/master...smarr:core-lib-update

**Comment by Hirevo** [comment]
> There are also the basic interpreter tests, see for my earlier attempt: https://github.com/Hirevo/som-rs/compare/master...smarr:core-lib-update

That's true, I should include these in this PR as well.  
They should be committed here shortly.

**Comment by Hirevo** [comment]
This PR has been rebased onto the branch from PR **#22**, in order to allow implementing `Symbol>>#=`.

This did fix the last failed test from the test suite, but the benchmarks from the latest core-lib commit seems to be broken when run with the parameters defined in the current `rebench.conf`.  
So, I think I will move back the core-lib to the same commit as in the Java SOM, which should address this.

**Comment by Hirevo** [comment]
This PR has now been rebased on latest master, following the merge of PR #22, on which it was previously based on.

**Pull request merged**
